export const sub4 = [
  {
    endTime: 58862,
    id: 1,
    phonetic: "həˈloʊ maɪ frɛndz aɪ æm pɔl ˈɡruːbɚ ənd ˈwɛlkəm bæk",
    speaker: "Paul Gruber:",
    startTime: 54649,
    text: "Hello, my friends, I am Paul Gruber and welcome back.",
    translation:
      "Xin chào các bạn, tôi là Paul Gruber và chào mừng các bạn quay trở lại.",
  },
  {
    endTime: 60958,
    id: 2,
    phonetic: "ɪn təˈdeɪz ˈvɪdioʊ klæs",
    speaker: "none",
    startTime: 58862,
    text: "In today's video class,",
    translation: "Trong buổi học qua video ngày hôm nay,",
  },
  {
    endTime: 70337,
    id: 3,
    phonetic:
      "wi ɑr ˈɡoʊɪŋ tə ˈkʌvɚ ði ɪkˈstriːmli ɪmˈpɔrtənt ˌʌnˈvɔɪst tiːˈeɪtʃ saʊndz æt ðə bɪˈɡɪnɪŋ əv wɝːdz",
    speaker: "none",
    startTime: 60958,
    text: "we are going to cover the extremely important unvoiced TH sounds at the beginning of words.",
    translation:
      "chúng ta sẽ học về những âm TH vô thanh cực kỳ quan trọng ở đầu từ.",
  },
  {
    endTime: 75556,
    id: 4,
    phonetic: "ˌʌnˈvɔɪst minz jɚ ˈvoʊkəl kɔrdz ɑr nɑt ˈvaɪbreɪtɪŋ",
    speaker: "none",
    startTime: 70337,
    text: "Unvoiced means your vocal cords are not vibrating.",
    translation: "“Vô thanh” có nghĩa là dây thanh quản của bạn không rung.",
  },
  {
    endTime: 77533,
    id: 5,
    phonetic: "naʊ ˈleɪtɚ ɑn ɪn ðə ˈtreɪnɪŋ",
    speaker: "none",
    startTime: 75556,
    text: "Now later on in the training,",
    translation: "Bây giờ, sau này trong buổi đào tạo,",
  },
  {
    endTime: 82330,
    id: 6,
    phonetic: "wɪl ˈkʌvɚ ˈʌðɚ taɪps əv tiːˈeɪtʃ saʊndz bət ðæts fər əˈnʌðɚ deɪ",
    speaker: "none",
    startTime: 77533,
    text: "we'll cover other types of TH sounds, but that's for another day.",
    translation:
      "chúng ta sẽ học các loại âm TH khác, nhưng để dành cho một ngày khác.",
  },
  {
    endTime: 86379,
    id: 7,
    phonetic: "ˈɛniˌweɪ ɪf ju wɪʃ tə spiːk klɪr ənd kəˈrɛkt ˈɪŋɡlɪʃ",
    speaker: "none",
    startTime: 82330,
    text: "Anyway, if you wish to speak clear and correct English,",
    translation: "Dù sao thì, nếu bạn muốn nói tiếng Anh rõ ràng và chuẩn xác,",
  },
  {
    endTime: 90625,
    id: 8,
    phonetic: "ju ˈrɪəli nid tə ˈmæstɚ ðɪs saʊnd",
    speaker: "none",
    startTime: 86379,
    text: "you really need to master this sound.",
    translation: "bạn thật sự cần thành thạo âm này.",
  },
  {
    endTime: 93115,
    id: 9,
    phonetic: "naʊ æz wi ɡɛt ˈstɑrtɪd təˈdeɪ",
    speaker: "none",
    startTime: 90625,
    text: "Now as we get started today,",
    translation: "Bây giờ khi chúng ta bắt đầu hôm nay,",
  },
  {
    endTime: 96554,
    id: 10,
    phonetic: "ju meɪ seɪ tə jɚˈsɛlf oʊ ðɪs ɪz ɪmˈpɑsəbəl",
    speaker: "none",
    startTime: 93115,
    text: "you may say to yourself, oh, this is impossible.",
    translation: "bạn có thể nghĩ: ôi, điều này là không thể.",
  },
  {
    endTime: 99692,
    id: 11,
    phonetic: "aɪl ˈnɛvɚ bi ˈeɪbəl tə du ðɪs wɛn aɪ spiːk ˈɪŋɡlɪʃ",
    speaker: "none",
    startTime: 96554,
    text: "I'll never be able to do this when I speak English.",
    translation:
      "Tôi sẽ không bao giờ có thể làm được điều này khi nói tiếng Anh.",
  },
  {
    endTime: 103483,
    id: 12,
    phonetic: "wɛl aɪ wɑnt ju tə noʊ ðæt trʌst mi ju wɪl",
    speaker: "none",
    startTime: 99692,
    text: "Well I want you to know that trust me, you will.",
    translation: "Tôi muốn bạn biết rằng, tin tôi đi, bạn sẽ làm được.",
  },
  {
    endTime: 109663,
    id: 13,
    phonetic:
      "wɪð ˈpræktɪs ˈmɪljənz əv maɪ ˈstudənts həv lɝnd tə pɚˈfɛkt ðɪs saʊnd",
    speaker: "none",
    startTime: 103483,
    text: "With practice, millions of my students have learned to perfect this sound",
    translation:
      "Với sự luyện tập, hàng triệu học viên của tôi đã học cách phát âm hoàn hảo âm này",
  },
  {
    endTime: 111687,
    id: 14,
    phonetic: "ənd wɛn ju ˈfaɪnəli ˈmæstɚ ðɪs",
    speaker: "none",
    startTime: 109663,
    text: "and when you finally master this,",
    translation: "và khi bạn cuối cùng cũng thành thạo được âm này,",
  },
  {
    endTime: 115808,
    id: 15,
    phonetic:
      "aɪm ˈtɛlɪŋ ju ɪt meɪks sʌtʃ ə ˈbjutəfəl ɪmˈpruvmənt ɪn jɚ ˈɪŋɡlɪʃ",
    speaker: "none",
    startTime: 111687,
    text: "I'm telling you it makes such a beautiful improvement in your English.",
    translation:
      "tôi nói thật với bạn, nó sẽ cải thiện tiếng Anh của bạn một cách tuyệt vời.",
  },
  {
    endTime: 118155,
    id: 16,
    phonetic: "ˈpipəl wɪl ˌʌndɚˈstænd ju ˈbɛtɚ",
    speaker: "none",
    startTime: 115808,
    text: "People will understand you better",
    translation: "Mọi người sẽ hiểu bạn rõ hơn",
  },
  {
    endTime: 121992,
    id: 17,
    phonetic: "ənd ju wɪl saʊnd soʊ mʌtʃ mɔr ˈpɑlɪʃt",
    speaker: "none",
    startTime: 118155,
    text: "and you will sound so much more polished.",
    translation: "và bạn sẽ phát âm nghe tự nhiên và chuẩn hơn nhiều.",
  },
  {
    endTime: 130041,
    id: 18,
    phonetic:
      "soʊ ju fɝst nid tə ˌʌndɚˈstænd ðæt ðə tiːˈeɪtʃ ɪz ə ˈfrɪkʃən saʊnd ˈfrɪkʃən oʊˈkeɪ",
    speaker: "none",
    startTime: 121992,
    text: "So you first need to understand that the TH is a friction sound, friction, okay?",
    translation:
      "Vì vậy, đầu tiên bạn cần hiểu rằng âm TH là một âm ma sát, ma sát, được chứ?",
  },
  {
    endTime: 131334,
    id: 19,
    phonetic: "soʊ wɛn jɚ ˈspiːkɪŋ",
    speaker: "none",
    startTime: 130041,
    text: "So when you're speaking,",
    translation: "Vì vậy, khi bạn đang nói,",
  },
  {
    endTime: 134786,
    id: 20,
    phonetic: "ðə ˈlɪsənɚ nidz tə hɪr ðæt ˈfrɪkʃən",
    speaker: "none",
    startTime: 131334,
    text: "the listener needs to hear that friction",
    translation: "người nghe cần nghe thấy âm ma sát đó",
  },
  {
    endTime: 137586,
    id: 21,
    phonetic: "ənd ɪt nidz tə bi ðə kəˈrɛkt ˈfrɪkʃən",
    speaker: "none",
    startTime: 134786,
    text: "and it needs to be the correct friction.",
    translation: "và nó cần phải là âm ma sát đúng.",
  },
  {
    endTime: 139857,
    id: 22,
    phonetic: "soʊ haʊ du ju kriˈeɪt ðæt",
    speaker: "none",
    startTime: 137586,
    text: "So how do you create that?",
    translation: "Vậy bạn tạo ra âm đó như thế nào?",
  },
  {
    endTime: 141827,
    id: 23,
    phonetic: "oʊˈkeɪ hɪr wi ɡoʊ aɪm ˈɡoʊɪŋ tə ʃoʊ ju",
    speaker: "none",
    startTime: 139857,
    text: "Okay, here we go. I'm going to show you.",
    translation: "Được rồi, bắt đầu nào. Tôi sẽ chỉ cho bạn.",
  },
  {
    endTime: 143953,
    id: 24,
    phonetic: "ˈfɜrst əv ɔl ju stɪk jʊr tʌŋ aʊt",
    speaker: "none",
    startTime: 141833,
    text: "First of all, you stick your tongue out",
    translation: "Trước tiên, bạn đưa lưỡi ra ngoài.",
  },
  {
    endTime: 151127,
    id: 25,
    phonetic:
      "ənd aɪ wɑnt ju tə baɪt daʊn ˈʤɛntli wɪð jʊr tiθ ˈɔntu ðə tɪp əv jʊr tʌŋ laɪk ðɪs",
    speaker: "none",
    startTime: 143953,
    text: "and I want you to bite down gently with your teeth onto the tip of your tongue like this.",
    translation:
      "và tôi muốn bạn nhẹ nhàng cắn đầu lưỡi bằng răng của bạn như thế này.",
  },
  {
    endTime: 153773,
    id: 26,
    phonetic: "soʊ jʊr ˈstɪkɪŋ aʊt jʊr tʌŋ ʤəst ə ˈlɪtl̩ bɪt",
    speaker: "none",
    startTime: 151127,
    text: "So you're sticking out your tongue just a little bit",
    translation: "Vì vậy bạn đang thè lưỡi ra một chút.",
  },
  {
    endTime: 158481,
    id: 27,
    phonetic: "ənd aɪ wʊd laɪk ju tə smaɪl laɪk ðæt",
    speaker: "none",
    startTime: 153773,
    text: "and I would like you to smile like that.",
    translation: "và tôi muốn bạn cười như vậy.",
  },
  {
    endTime: 161562,
    id: 28,
    phonetic: "naʊ teɪk ðə pɑm əv jʊr hænd",
    speaker: "none",
    startTime: 158481,
    text: "Now, take the palm of your hand,",
    translation: "Bây giờ, hãy đưa lòng bàn tay của bạn ra,",
  },
  {
    endTime: 167761,
    id: 29,
    phonetic:
      "pʊt ɪt ɪn frʌnt əv jʊr maʊθ ənd ɪˈmæʤən ju ɑr ˈbloʊɪŋ aʊt jʊr ˈbɜrθˌdeɪ ˈkændlz",
    speaker: "none",
    startTime: 161562,
    text: "put it in front of your mouth and imagine you are blowing out your birthday candles",
    translation:
      "đặt nó trước miệng và tưởng tượng bạn đang thổi nến sinh nhật.",
  },
  {
    endTime: 171200,
    id: 30,
    phonetic: "ənd aɪ wɑnt ju tə ˈsɪmpli bloʊ ˈɔntu jʊr hænd",
    speaker: "none",
    startTime: 167761,
    text: "and I want you to simply blow onto your hand.",
    translation:
      "và tôi muốn bạn chỉ đơn giản là thổi vào lòng bàn tay của mình.",
  },
  {
    endTime: 174114,
    id: 31,
    phonetic: "ðæts wɛr ðə ˈfoʊkəs ɪz ˈbloʊɪŋ ɑn jʊr hænd",
    speaker: "none",
    startTime: 171200,
    text: "That's where the focus is, blowing on your hand",
    translation: "Đó là nơi bạn nên tập trung, thổi vào tay bạn.",
  },
  {
    endTime: 177957,
    id: 32,
    phonetic: "waɪl jʊr ˈkipɪŋ jʊr tʌŋ aʊt ə ˈlɪtl̩ bɪt bɪˈtwin jʊr tiθ",
    speaker: "nnone",
    startTime: 174114,
    text: "while you're keeping your tongue out a little bit between your teeth.",
    translation:
      "trong khi bạn giữ lưỡi thè ra một chút giữa các răng của mình.",
  },
  {
    endTime: 183616,
    id: 33,
    phonetic: "wɑʧ mi laɪk ðæt",
    speaker: "none",
    startTime: 177957,
    text: "Watch me. Like that.",
    translation: "Nhìn tôi này. Như vậy đó.",
  },
  {
    endTime: 186198,
    id: 34,
    phonetic: "doʊnt ˈfoʊkəs soʊ mʌʧ ɑn jʊr maʊθ",
    speaker: "none",
    startTime: 183616,
    text: "Don't focus so much on your mouth.",
    translation: "Đừng tập trung quá nhiều vào miệng của bạn.",
  },
  {
    endTime: 192045,
    id: 35,
    phonetic: "ʤəst ˈfoʊkəs ɑn ˈbloʊɪŋ ɑn jʊr hænd laɪk ðæt",
    speaker: "none",
    startTime: 186198,
    text: "Just focus on blowing on your hand. Like that.",
    translation: "Chỉ cần tập trung vào việc thổi vào tay bạn. Như vậy.",
  },
  {
    endTime: 198814,
    id: 36,
    phonetic: "naʊ ˈsloʊli aɪ wɑnt ju tu æd ən ɑː saʊnd ˈæftɚ ðə θ",
    speaker: "none",
    startTime: 192045,
    text: "Now, slowly, I want you to add an ah sound after the th",
    translation: 'Bây giờ, từ từ, tôi muốn bạn thêm âm "a" sau âm "th"',
  },
  {
    endTime: 207086,
    id: 37,
    phonetic: "ənd ˈoʊpən jʊr maʊθ laɪk ðɪs",
    speaker: "none",
    startTime: 198814,
    text: "and open your mouth like this.",
    translation: "và mở miệng của bạn ra như thế này.",
  },
  {
    endTime: 209388,
    id: 38,
    phonetic: "steɪ rɪˈlækst",
    speaker: "none",
    startTime: 207257,
    text: "Stay relaxed.",
    translation: "Hãy thư giãn.",
  },
  {
    endTime: 214303,
    id: 39,
    phonetic: "aɪ doʊnt wɑnt ju tə tɛns ʌp ənd seɪ",
    speaker: "none",
    startTime: 209455,
    text: "I don't want you to tense up and say,",
    translation: "Tôi không muốn bạn căng thẳng và nói,",
  },
  {
    endTime: 216664,
    id: 40,
    phonetic: "wɛr jʊr ˈædɪŋ ə ˈlɪtl̩ ti saʊnd ɪn ðɛr",
    speakerr: "none",
    startTime: 214303,
    text: "where you're adding a little t sound in there.",
    translation: 'nơi bạn thêm một âm "t" nhỏ vào trong đó.',
  },
  {
    endTime: 219265,
    id: 41,
    phonetic: "sʌm ˈpipəl du ðæt ənd ðæt ɪz rɔŋ",
    speaker: "none",
    startTime: 216664,
    text: "Some people do that and that is wrong.",
    translation: "Một số người làm vậy và điều đó là sai.",
  },
  {
    endTime: 220884,
    id: 42,
    phonetic: "ʤəst steɪ rɪˈlækst",
    speaker: "none",
    startTime: 219265,
    text: "Just stay relaxed,",
    translation: "Chỉ cần thư giãn,",
  },
  {
    endTime: 228511,
    id: 43,
    phonetic: "ˈsloʊli ˈoʊpən jʊr maʊθ waɪl jʊr ˈbloʊɪŋ ɑn jʊr hænd",
    speaker: "none",
    startTime: 220884,
    text: "slowly open your mouth while you're blowing on your hand.",
    translation: "từ từ mở miệng trong khi bạn thổi vào tay mình.",
  },
  {
    endTime: 232603,
    id: 44,
    phonetic: "ðæts haʊ ju meɪk ðə ˈpɜrfɪkt ti-eɪʧ saʊnd",
    speaker: "none",
    startTime: 228511,
    text: "That's how you make the perfect th sound.",
    translation: "Đó là cách bạn tạo ra âm th hoàn hảo.",
  },
  {
    endTime: 236988,
    id: 45,
    phonetic: "ˌoʊˈkeɪ naʊ lɛts lʊk ət ðɪs wɜrd rɪˈpit ˈæftɚ mi",
    speaker: "none",
    startTime: 232603,
    text: "Okay, now let's look at this word. Repeat after me.",
    translation: "Được rồi, bây giờ hãy nhìn vào từ này. Lặp lại theo tôi.",
  },
  {
    endTime: 243628,
    id: 46,
    phonetic: "θɪŋk θɪŋk",
    speaker: "none",
    startTime: 236988,
    text: "Think. Think.",
    translation: "Nghĩ. Nghĩ.",
  },
  {
    endTime: 248566,
    id: 47,
    phonetic: "ju si ɪts nɑt θɪŋk θɪŋk θɪŋk",
    speaker: "none",
    startTime: 243628,
    text: "You see, it's not think. Think. Think.",
    translation: 'Bạn thấy đấy, đó không phải là "think". Think. Think.',
  },
  {
    endTime: 250509,
    id: 48,
    phonetic: "ju nid ðæt ɛr ˈkʌmɪŋ aʊt",
    speaker: "none",
    startTime: 248566,
    text: "You need that air coming out.",
    translation: "Bạn cần luồng không khí đó thổi ra.",
  },
  {
    endTime: 252985,
    id: 49,
    phonetic: "ɪts θɪŋk",
    speaker: "none",
    startTime: 250509,
    text: "It's think.",
    translation: 'Đó là "think".',
  },
  {
    endTime: 256386,
    id: 50,
    phonetic: "bloʊ ðə ti-eɪʧ ˈɔntu jʊr hænd",
    speaker: "none",
    startTime: 252985,
    text: "Blow the th onto your hand.",
    translation: "Thổi âm th vào lòng bàn tay của bạn.",
  },
  {
    endTime: 259938,
    id: 51,
    phonetic: "ðæt ɪz ðə bɛst trɪk ðɛr ɪz rɪˈgɑrdɪŋ ðə ti-eɪʧ",
    speaker: "none",
    startTime: 256386,
    text: "That is the best trick there is regarding the th.",
    translation: "Đó là mẹo hay nhất về âm th.",
  },
  {
    endTime: 266564,
    id: 52,
    phonetic:
      "ʤəst juz jʊr hænd ənd ˈpræktəs ðɪs ˈbloʊɪŋ tɛkˈnik ɑn iʧ wʌn əv ðiz wɜrdz",
    speaker: "none",
    startTime: 259938,
    text: "Just use your hand and practice this blowing technique on each one of these words.",
    translation:
      "Chỉ cần dùng tay của bạn và luyện tập kỹ thuật thổi này trên từng từ một.",
  },
  {
    endTime: 267930,
    id: 53,
    phonetic: "rɪˈpit ˈæftɚ mi",
    speaker: "none",
    startTime: 266564,
    text: "Repeat after me.",
    translation: "Lặp lại theo tôi.",
  },
  {
    endTime: 271580,
    id: 54,
    phonetic: "θæŋks",
    speaker: "none",
    startTime: 267930,
    text: "Thanks.",
    translation: "Cảm ơn.",
  },
  {
    endTime: 274035,
    id: 55,
    phonetic: "θʌm",
    speaker: "none",
    startTime: 271580,
    text: "Thumb.",
    translation: "Ngón tay cái.",
  },
  {
    endTime: 276393,
    id: 56,
    phonetic: "wɪʧ ɪz ðɪs maɪ θʌm",
    speaker: "none",
    startTime: 274035,
    text: "Which is this, my thumb.",
    translation: "Chính là cái này, ngón tay cái của tôi.",
  },
  {
    endTime: 279035,
    id: 57,
    phonetic: "ˈθɜrti",
    speaker: "none",
    startTime: 276393,
    text: "Thirty.",
    translation: "Ba mươi.",
  },
  {
    endTime: 281545,
    id: 58,
    phonetic: "θɪŋ",
    speaker: "none",
    startTime: 279064,
    text: "Thing.",
    translation: "Vật.",
  },
  {
    endTime: 284666,
    id: 59,
    phonetic: "θɪn",
    speaker: "none",
    startTime: 281545,
    text: "Thin.",
    translation: "Gầy.",
  },
  {
    endTime: 287452,
    id: 60,
    phonetic: "θɪk",
    speaker: "none",
    startTime: 284666,
    text: "Thick.",
    translation: "Dày.",
  },
  {
    endTime: 290518,
    id: 61,
    phonetic: "ˈθɪri",
    speaker: "none",
    startTime: 287452,
    text: "Theory.",
    translation: "Lý thuyết.",
  },
  {
    endTime: 293461,
    id: 62,
    phonetic: "ˈθʌndɚ",
    speaker: "none",
    startTime: 290518,
    text: "Thunder.",
    translation: "Sấm.",
  },
  {
    endTime: 296132,
    id: 63,
    phonetic: "θif",
    speaker: "none",
    startTime: 293461,
    text: "Thief.",
    translation: "Kẻ trộm.",
  },
  {
    endTime: 298869,
    id: 64,
    phonetic: "θɔrn",
    speaker: "none",
    startTime: 296132,
    text: "Thorn.",
    translation: "Gai.",
  },
  {
    endTime: 301679,
    id: 65,
    phonetic: "ˈθɜrməl",
    speaker: "none",
    startTime: 298869,
    text: "Thermal.",
    translation: "Nhiệt.",
  },
  {
    endTime: 304144,
    id: 66,
    phonetic: "θim",
    speaker: "none",
    startTime: 301679,
    text: "Theme.",
    translation: "Chủ đề.",
  },
  {
    endTime: 306602,
    id: 67,
    phonetic: "ˈɪzənt ðɪs fʌn",
    speaker: "none",
    startTime: 304144,
    text: "Isn't this fun?",
    translation: "Có phải điều này rất vui không?",
  },
  {
    endTime: 308167,
    id: 68,
    phonetic: "jʊr ˈduɪŋ ˈvɛri ɡʊd",
    speaker: "none",
    startTime: 306602,
    text: "You're doing very good.",
    translation: "Bạn đang làm rất tốt.",
  },
  {
    endTime: 314274,
    id: 69,
    phonetic:
      "naʊ mit mi ɪn ðə nɛkst ˈvɪdioʊ ənd wi wɪl wɜrk ɑn ti-eɪʧ ˈsɛntənsɪz",
    speaker: "none",
    startTime: 308167,
    text: "Now, meet me in the next video and we will work on th sentences.",
    translation:
      "Bây giờ, gặp tôi ở video tiếp theo và chúng ta sẽ luyện các câu có âm th.",
  },
  {
    endTime: 315631,
    id: 70,
    phonetic: "aɪl si ju ðɛr",
    speaker: "none",
    startTime: 314274,
    text: "I'll see you there.",
    translation: "Tôi sẽ gặp bạn ở đó.",
  },
];
