export const sub5 = [
  {
    endTime: 1174,
    id: 1,
    phonetic: "həˈloʊ",
    speaker: "Paul Gruber:",
    startTime: 90,
    text: "Hello.",
    translation: "Xin chào.",
  },
  {
    endTime: 6269,
    id: 2,
    phonetic:
      "oʊˈkeɪ naʊ aɪm ˈɡoʊɪŋ tə ɡɪv ju səm ˈsɛntənsɪz wɪð ˌtiːˈeɪtʃ wɝːdz",
    speaker: "none",
    startTime: 1174,
    text: "Okay, now I'm going to give you some sentences with TH words.",
    translation:
      "Được rồi, bây giờ tôi sẽ đưa cho bạn một số câu có chứa các từ có âm TH.",
  },
  {
    endTime: 9963,
    id: 3,
    phonetic: "lɛts ɡoʊ θru ðɛm ˈvɛri ˈsloʊli",
    speaker: "none",
    startTime: 6269,
    text: "Let's go through them very slowly.",
    translation: "Chúng ta hãy cùng đi qua chúng thật chậm rãi.",
  },
  {
    endTime: 14744,
    id: 4,
    phonetic: "aɪ noʊ ˈmeɪkɪŋ ðiːz ˌtiːˈeɪtʃ saʊndz meɪ fiːl ə bɪt wɪrd tə ju",
    speaker: "none",
    startTime: 10035,
    text: "I know making these TH sounds may feel a bit weird to you,",
    translation:
      "Tôi biết việc tạo ra các âm TH này có thể khiến bạn cảm thấy hơi lạ.",
  },
  {
    endTime: 19683,
    id: 5,
    phonetic:
      "bət ðɪs ɪz ɪɡˈzæktli haʊ ˈneɪtɪv ˈɪŋɡlɪʃ ˈspiːkərz spiːk ˈɪŋɡlɪʃ",
    speaker: "none",
    startTime: 14744,
    text: "but this is exactly how native English speakers speak English.",
    translation: "nhưng đây chính xác là cách người bản xứ nói tiếng Anh.",
  },
  {
    endTime: 26090,
    id: 6,
    phonetic:
      "əˈɡɛn æz aɪ sɛd ˈɜrliər ɪt ˈrɪli hɛlps ɪf ju bloʊ ɑn jʊr hænd fɔr ˈɛvri ˌtiːˈeɪtʃ wɝːd",
    speaker: "none",
    startTime: 19683,
    text: "Again, as I said earlier, it really helps if you blow on your hand for every TH word.",
    translation:
      "Một lần nữa, như tôi đã nói trước đó, việc thổi vào tay cho mỗi từ TH thực sự có ích.",
  },
  {
    endTime: 30995,
    id: 7,
    phonetic: "ɪt ˈfɔrsɪz ju tə meɪk ðə ˈpɜrfɪkt klɪr ˌtiːˈeɪtʃ saʊnd",
    speaker: "none",
    startTime: 26090,
    text: "It forces you to make the perfect, clear TH sound.",
    translation: "Nó bắt bạn phải tạo ra âm TH rõ ràng và hoàn hảo.",
  },
  {
    endTime: 32982,
    id: 8,
    phonetic: "lɛts teɪk ə lʊk ət ðɪs ˈsɛntəns",
    speaker: "none",
    startTime: 30995,
    text: "Let's take a look at this sentence,",
    translation: "Hãy cùng xem câu này nhé,",
  },
  {
    endTime: 36575,
    id: 9,
    phonetic: "bət fɜrst lɛts rɪˈvju ði ʌnˈvɔɪst ˌtiːˈeɪtʃ wɝːdz",
    speaker: "none",
    startTime: 32982,
    text: "but first let's review the unvoiced TH words,",
    translation: "nhưng trước tiên hãy ôn lại các từ TH vô thanh,",
  },
  {
    endTime: 38838,
    id: 10,
    phonetic: "ənd ðɛn wil pʊt ˈɛvriθɪŋ təˈɡɛðər",
    speaker: "none",
    startTime: 36575,
    text: "and then we'll put everything together.",
    translation: "và sau đó chúng ta sẽ kết hợp mọi thứ lại với nhau.",
  },
  {
    endTime: 42760,
    id: 11,
    phonetic:
      "naʊ ju meɪ ˈnoʊtɪs ðæt aɪm ˈskɪpɪŋ ˈoʊvər səm əv ðə ˌtiːˈeɪtʃ wɝːdz",
    speaker: "none",
    startTime: 38838,
    text: "Now you may notice that I'm skipping over some of the TH words,",
    translation:
      "Giờ bạn có thể nhận thấy rằng tôi đang bỏ qua một số từ có âm TH,",
  },
  {
    endTime: 47387,
    id: 12,
    phonetic: "ənd ðæts bɪˈkəz ə fju əv ðɛm hæv ðæt vɔɪst ˌtiːˈeɪtʃ saʊnd",
    speaker: "none",
    startTime: 42760,
    text: "and that's because a few of them have that voiced TH sound,",
    translation: "và đó là vì một vài từ trong số đó có âm TH hữu thanh,",
  },
  {
    endTime: 51137,
    id: 13,
    phonetic: "ənd wil bi ˈkʌvərɪŋ ðoʊz ɪmˈpɔrtnt saʊndz ɪn ə ˈfjuʧər ˈjuːnɪt",
    speaker: "none",
    startTime: 47387,
    text: "and we'll be covering those important sounds in a future unit,",
    translation:
      "và chúng ta sẽ học những âm quan trọng đó trong một phần sau,",
  },
  {
    endTime: 52880,
    id: 14,
    phonetic: "dʒəst ɪn keɪs jʊr ˈwʌndərɪŋ",
    speaker: "none",
    startTime: 51137,
    text: "just in case you're wondering.",
    translation: "chỉ để phòng trường hợp bạn đang thắc mắc.",
  },
  {
    endTime: 54977,
    id: 15,
    phonetic: "oʊˈkeɪ rɪˈpiːt ˈæftər mi",
    speaker: "none",
    startTime: 52880,
    text: "Okay, repeat after me.",
    translation: "Được rồi, hãy lặp lại theo tôi.",
  },
  {
    endTime: 66380,
    id: 16,
    phonetic: "ˈθɛlmə θæŋk θɪk θaɪz",
    speaker: "none",
    startTime: 54977,
    text: "Thelma, thank, thick, thighs.",
    translation: "Thelma, cảm ơn, dày, đùi.",
  },
  {
    endTime: 81475,
    id: 17,
    phonetic: "ˈθɛlmə sɛd θæŋk ju wɛn ʃi eɪt ðə θɪk ˈbɑrbɪˌkju ˈʧɪkən θaɪz",
    speaker: "none",
    startTime: 66380,
    text: "Thelma said thank you when she ate the thick barbecue chicken thighs.",
    translation: "Thelma đã nói cảm ơn khi cô ấy ăn đùi gà nướng dày.",
  },
  {
    endTime: 101385,
    id: 18,
    phonetic: "ˈθɔtfəl θɪŋ θɔt ˌθæŋksˈɡɪvɪŋ θiːmd",
    speaker: "none",
    startTime: 84762,
    text: "Thoughtful, thing, thought, Thanksgiving, themed.",
    translation: "Chu đáo, điều, suy nghĩ, Lễ Tạ Ơn, theo chủ đề.",
  },
  {
    endTime: 115681,
    id: 19,
    phonetic: "ðə ˈθɔtfəl θɪŋ aɪ θɔt əˈbaʊt wəz ðɛr ˌθæŋksˈɡɪvɪŋ θiːmd ˈpɑrti",
    speaker: "none",
    startTime: 101385,
    text: "The thoughtful thing I thought about was their Thanksgiving-themed party.",
    translation:
      "Điều chu đáo mà tôi đã nghĩ đến là bữa tiệc theo chủ đề Lễ Tạ Ơn của họ.",
  },
  {
    endTime: 140089,
    id: 20,
    phonetic: "ˈθɜrzdeɪ ˈθɛrəpɪst θɔt θɪk θərˈmɑmətərz θivz",
    speaker: "none",
    startTime: 120785,
    text: "Thursday, therapist, thought, thick, thermometers, thieves.",
    translation:
      "Thứ Năm, nhà trị liệu, suy nghĩ, dày, nhiệt kế, những tên trộm.",
  },
  {
    endTime: 159373,
    id: 21,
    phonetic:
      "ɑn ˈθɜrzdeɪ ðə ˈθɛrəpɪst θɔt ðæt ðə θɪk θərˈmɑmətərz wɜr ˈstoʊlən baɪ θivz",
    speaker: "none",
    startTime: 140089,
    text: "On Thursday, the therapist thought that the thick thermometers were stolen by thieves.",
    translation:
      "Vào thứ Năm, nhà trị liệu nghĩ rằng những cái nhiệt kế dày đã bị đánh cắp bởi những tên trộm.",
  },
  {
    endTime: 168055,
    id: 22,
    phonetic: "jʊr ˈsaʊndɪŋ ɡreɪt",
    speaker: "none",
    startTime: 165947,
    text: "You're sounding great.",
    translation: "Bạn đang phát âm rất tốt.",
  },
  {
    endTime: 169738,
    id: 23,
    phonetic: "nɛkst wʌn",
    speaker: "none",
    startTime: 168055,
    text: "Next one.",
    translation: "Tiếp theo.",
  },
  {
    endTime: 183142,
    id: 24,
    phonetic: "ˈθiədɔr θɪn ˈθɜrti ˈθaɪrɔɪd",
    speaker: "none",
    startTime: 169738,
    text: "Theodore, thin, 30, thyroid.",
    translation: "Theodore, gầy, ba mươi, tuyến giáp.",
  },
  {
    endTime: 200472,
    id: 25,
    phonetic:
      "ˈθiədɔr hu wəz ə ˈvɛri θɪn mæn peɪd ˈoʊnli ˈθɜrti-ˈdɒləz fɔr hɪz ˈθaɪrɔɪd ɪɡˈzæm",
    speaker: "none",
    startTime: 183910,
    text: "Theodore, who was a very thin man, paid only $30 for his thyroid exam.",
    translation:
      "Theodore, một người đàn ông rất gầy, chỉ trả 30 đô la cho bài kiểm tra tuyến giáp của anh ấy.",
  },
  {
    endTime: 226694,
    id: 26,
    phonetic:
      "ˈθɑnoʊ ˈθiːsɪs ˈθɜroʊ ˈθaʊzənd ðæts ə ˈvɛri ˈkɑmən wɝd ɪts nɑt ˈθaʊzənd ɪts ˈθaʊzənd",
    speaker: "none",
    startTime: 207960,
    text: "Thano, thesis, thorough, thousand. That's a very common word. It's not thousand, it's thousand.",
    translation:
      'Thano, luận án, kỹ lưỡng, một nghìn. Đó là một từ rất phổ biến. Không phải là "thousand" mà là "thousand".',
  },
  {
    endTime: 242549,
    id: 27,
    phonetic: "ˈθɑnoʊz ˈθiːsɪs wəz ˈθɜroʊ ənd kənˈteɪnd faɪv-ˈθaʊzənd wɝdz",
    speaker: "none",
    startTime: 226694,
    text: "Thano's thesis was thorough and contained 5,000 words.",
    translation: "Luận án của Thano rất kỹ lưỡng và chứa 5.000 từ.",
  },
  {
    endTime: 255493,
    id: 28,
    phonetic: "ˈθætʃər ˈθɔtfəl ˈθɛrəpi",
    speaker: "none",
    startTime: 244894,
    text: "Thatcher, thoughtful, therapy.",
    translation: "Thatcher, chu đáo, liệu pháp.",
  },
  {
    endTime: 269359,
    id: 29,
    phonetic:
      "ˈmɪstər ˈθætʃər wəz ˈvɛri ˈθɔtfəl tə peɪ fɔr ðiz ˈθɛrəpi ˈsɛʃənz",
    speaker: "none",
    startTime: 255674,
    text: "Mr. Thatcher was very thoughtful to pay for these therapy sessions.",
    translation:
      "Ông Thatcher rất chu đáo khi trả tiền cho các buổi trị liệu này.",
  },
  {
    endTime: 281259,
    id: 30,
    phonetic: "θiːmz ˈθiətər",
    speaker: "none",
    startTime: 274194,
    text: "Themes, theater.",
    translation: "Chủ đề, nhà hát.",
  },
  {
    endTime: 294507,
    id: 31,
    phonetic:
      "ðoʊz ˈmjuzɪkəl θiːmz meɪk ðə ˈbrʌðərz fiːl laɪk ðeɪ ɑr ɪn ə ˈθiətər",
    speaker: "none",
    startTime: 281744,
    text: "Those musical themes make the brothers feel like they are in a theater.",
    translation:
      "Những chủ đề âm nhạc đó khiến các anh em cảm thấy như đang ở trong một nhà hát.",
  },
  {
    endTime: 302369,
    id: 32,
    phonetic: "ˈvɛri ɡʊd ju ɑr ˈduɪŋ ɡreɪt",
    speaker: "none",
    startTime: 299982,
    text: "Very good, you are doing great.",
    translation: "Rất tốt, bạn đang làm rất tuyệt vời.",
  },
  {
    endTime: 309454,
    id: 33,
    phonetic:
      "ˈpræktɪs ðiːz ˈsɛntənsɪz ˈsloʊli ˈjuːzɪŋ jʊr hænd tə bloʊ aʊt ɔl ðoʊz ˌtiːˈeɪtʃ saʊndz",
    speaker: "none",
    startTime: 302369,
    text: "Practice these sentences slowly, using your hand to blow out all those TH sounds.",
    translation:
      "Luyện tập các câu này một cách chậm rãi, dùng tay bạn để thổi ra tất cả các âm TH đó.",
  },
  {
    endTime: 312826,
    id: 34,
    phonetic: "wəns jʊr bɪˈɡɪnɪŋ tə fiːl ˈkʌmfərtəbəl ˈduɪŋ ðɪs",
    speaker: "none",
    startTime: 309454,
    text: "Once you're beginning to feel comfortable doing this,",
    translation: "Khi bạn bắt đầu cảm thấy thoải mái khi làm điều này,",
  },
  {
    endTime: 319008,
    id: 35,
    phonetic:
      "ðɛn miːt mi ɪn ðə nɛkst ˈvɪdioʊ wɛr wɪr ˈɡoʊɪŋ tə ˈpræktɪs wɪð spiːd ənd ˈækjərəsi",
    speaker: "none",
    startTime: 312826,
    text: "then meet me in the next video where we're going to practice with speed and accuracy",
    translation:
      "thì gặp tôi ở video tiếp theo, nơi chúng ta sẽ luyện tập với tốc độ và độ chính xác",
  },
  {
    endTime: 324870,
    id: 36,
    phonetic:
      "tə hɛlp ju ˈkæri ðɪs nu skɪl ˈoʊvər ˈɪntu jʊr ˈɛvrideɪ ˌkɑnvərˈseɪʃənz",
    speaker: "none",
    startTime: 319008,
    text: "to help you carry this new skill over into your everyday conversations.",
    translation:
      "để giúp bạn mang kỹ năng mới này vào trong các cuộc hội thoại hàng ngày.",
  },
  {
    endTime: 326666,
    id: 37,
    phonetic: "aɪl miːt ju ðɛr",
    speaker: "none",
    startTime: 324870,
    text: "I'll meet you there.",
    translation: "Tôi sẽ gặp bạn ở đó.",
  },
];
