import { SubtitleEntry } from "../types";
import { sub4 } from "../lib/sub4";
import { sub5 } from "../lib/sub5";

export const subtitle2: SubtitleEntry[] = [
  {
    id: 1,
    startTime: 0,
    endTime: 6229,
    text: "Hey there. OK, let's take a look at some hidden y's in sentences.",
    phonetic: "heɪ ðɛr oʊˈkeɪ lɛts teɪk ə lʊk æt səm ˈhɪdən waɪz ɪn ˈsɛntənsɪz",
    translation:
      "Chào bạn. Được rồi, hãy xem qua một số âm 'y' ẩn trong các câu.",
    speaker: "Paul Gruber:",
  },
  {
    id: 2,
    startTime: 6229,
    endTime: 12104,
    text: "First, though, let's practice repeating the target words, and then we'll put it all together.",
    phonetic:
      "fɜrst ðoʊ lɛts ˈpræktəs rɪˈpitɪŋ ðə ˈtɑrɡət wɜrdz ənd ðɛn wɪl pʊt ɪt ɔl təˈɡɛðər",
    translation:
      "Trước tiên, hãy luyện tập lặp lại các từ mục tiêu, rồi sau đó chúng ta sẽ ghép chúng lại với nhau.",
    speaker: "none",
  },
  {
    id: 3,
    startTime: 12104,
    endTime: 13874,
    text: "Repeat after me.",
    phonetic: "rɪˈpit ˈæftər mi",
    translation: "Lặp lại theo tôi nhé.",
    speaker: "none",
  },
  {
    id: 4,
    startTime: 13874,
    endTime: 27201,
    text: "Radio, oil, area",
    phonetic: "ˈreɪdiˌoʊ ɔɪl ˈɛriə",
    translation:
      "Bản tin radio đưa tin rằng dầu đã được phát hiện ở một khu vực mới.",
    speaker: "none",
  },
  {
    id: 5,
    startTime: 27201,
    endTime: 42910,
    text: "The radio news reported that oil was discovered in a new area.",
    phonetic: "ðə ˈreɪdiˌoʊ nuz rɪˈpɔrtəd ðæt ɔɪl wəz dɪˈskʌvərd ɪn ə nu ˈɛriə",
    translation:
      "Bản tin radio đưa tin rằng dầu đã được phát hiện ở một khu vực mới.",
    speaker: "none",
  },
  {
    id: 6,
    startTime: 42910,
    endTime: 54201,
    text: "The radio news reported that oil was discovered in a new area.",
    phonetic: "ðə ˈreɪdiˌoʊ nuz rɪˈpɔrtəd ðæt ɔɪl wəz dɪˈskʌvərd ɪn ə nu ˈɛriə",
    translation:
      "Bản tin radio đưa tin rằng dầu đã được phát hiện ở một khu vực mới.",
    speaker: "none",
  },
  {
    id: 7,
    startTime: 54201,
    endTime: 6229,
    text: "The radio news reported that oil was discovered in a new area.",
    phonetic: "ðə ˈreɪdiˌoʊ nuz rɪˈpɔrtəd ðæt ɔɪl wəz dɪˈskʌvərd ɪn ə nu ˈɛriə",
    translation:
      "Bản tin radio đưa tin rằng dầu đã được phát hiện ở một khu vực mới.",
    speaker: "none",
  },
  {
    id: 8,
    startTime: 6229,
    endTime: 7469,
    text: "Broiled, oil, while.",
    phonetic: "brɔɪld ɔɪl waɪl",
    translation: "Nướng, dầu, một lúc.",
    speaker: "none",
  },
  {
    id: 9,
    startTime: 7469,
    endTime: 8609,
    text: "We haven't broiled fish using olive oil in a while.",
    phonetic: "wi ˈhævənt brɔɪld fɪʃ ˈjuzɪŋ ˈɑlɪv ɔɪl ɪn ə waɪl",
    translation:
      "Chúng tôi chưa nướng cá bằng dầu ô liu trong một thời gian rồi.",
    speaker: "none",
  },
  {
    id: 10,
    startTime: 8609,
    endTime: 9749,
    text: "Smile, wireless, videos.",
    phonetic: "smaɪl ˈwaɪərləs ˈvɪdiˌoʊz",
    translation: "Cười, không dây, video.",
    speaker: "none",
  },
];

export const subtitle3: SubtitleEntry[] = [
  {
    id: 1,
    startTime: 54000,
    endTime: 58233,
    text: "Hello, my friend, it's Paul Gruber once again.",
    phonetic: "həˈloʊ maɪ frɛnd ɪts pɔl ˈɡruːbər wʌns əˈɡɛn",
    translation: "Chào bạn của tôi, lại là Paul Gruber đây.",
    speaker: "Paul Gruber:",
  },
  {
    id: 2,
    startTime: 58475,
    endTime: 60286,
    text: "I hope you are doing well.",
    phonetic: "aɪ hoʊp ju ɑr ˈduɪŋ wɛl",
    translation: "Tôi hy vọng bạn vẫn ổn.",
    speaker: "none",
  },
  {
    id: 3,
    startTime: 60476,
    endTime: 67039,
    text: "In today's video class, we will explore hidden Y sounds.",
    phonetic: "ɪn təˈdeɪz ˈvɪdiˌoʊ klæs wi wɪl ɪkˈsplɔr ˈhɪdən waɪ saʊndz",
    translation:
      "Trong buổi học video hôm nay, chúng ta sẽ khám phá những âm Y ẩn.",
    speaker: "none",
  },
  {
    id: 4,
    startTime: 67039,
    endTime: 72265,
    text: "Now, you've probably never heard about hidden sounds in English,",
    phonetic: "naʊ juv ˈprɑbəbli ˈnɛvər hɜrd əˈbaʊt ˈhɪdən saʊndz ɪn ˈɪŋɡlɪʃ",
    translation:
      "Giờ thì có lẽ bạn chưa bao giờ nghe về những âm ẩn trong tiếng Anh,",
    speaker: "none",
  },
  {
    id: 5,
    startTime: 72265,
    endTime: 79298,
    text: "because English schools and English teachers, even English books, never speak about them.",
    phonetic:
      "bɪˈkəz ˈɪŋɡlɪʃ skuːlz ənd ˈɪŋɡlɪʃ ˈtiʧərz ˈivɪn ˈɪŋɡlɪʃ bʊks ˈnɛvər spiːk əˈbaʊt ðɛm",
    translation:
      "bởi vì các trường tiếng Anh, giáo viên tiếng Anh, thậm chí sách tiếng Anh, không bao giờ nói về chúng.",
    speaker: "none",
  },
  {
    id: 6,
    startTime: 79490,
    endTime: 81365,
    text: "But they certainly exist,",
    phonetic: "bət ðeɪ ˈsɜrtənli ɪɡˈzɪst",
    translation: "Nhưng chúng chắc chắn tồn tại,",
    speaker: "none",
  },
  {
    id: 7,
    startTime: 81365,
    endTime: 86316,
    text: "and they are an important part in North American pronunciation.",
    phonetic: "ənd ðeɪ ɑr ən ɪmˈpɔrtənt pɑrt ɪn nɔrθ əˈmɛrɪkən prəˌnʌnsiˈeɪʃən",
    translation: "và chúng là một phần quan trọng trong cách phát âm Bắc Mỹ.",
    speaker: "none",
  },
  {
    id: 8,
    startTime: 86316,
    endTime: 89716,
    text: "The good news is they are easy to learn,",
    phonetic: "ðə ɡʊd nuːz ɪz ðeɪ ɑr ˈiːzi tə lɜrn",
    translation: "Tin tốt là chúng dễ học,",
    speaker: "none",
  },
  {
    id: 9,
    startTime: 89716,
    endTime: 94605,
    text: "and when you use them, they will make you more understandable,",
    phonetic: "ənd wɛn ju juːz ðəm ðeɪ wɪl meɪk ju mɔr ˌʌndərˈstændəbəl",
    translation: "và khi bạn sử dụng chúng, bạn sẽ được hiểu dễ hơn,",
    speaker: "none",
  },
  {
    id: 10,
    startTime: 94605,
    endTime: 99341,
    text: "and your English will sound much closer to that of a native speaker.",
    phonetic:
      "ənd jʊr ˈɪŋɡlɪʃ wɪl saʊnd mʌʧ ˈkloʊsər tə ðæt əv ə ˈneɪtɪv ˈspiːkər",
    translation: "và tiếng Anh của bạn sẽ nghe giống người bản xứ hơn nhiều.",
    speaker: "none",
  },
  {
    id: 11,
    startTime: 99341,
    endTime: 102149,
    text: "Now, what do I mean by hidden?",
    phonetic: "naʊ wʌt də aɪ miːn baɪ ˈhɪdən",
    translation: 'Giờ, tôi muốn nói gì khi nói "ẩn"?',
    speaker: "none",
  },
  {
    id: 12,
    startTime: 102149,
    endTime: 103980,
    text: "Well, let me explain.",
    phonetic: "wɛl lɛt mi ɪkˈspleɪn",
    translation: "Vậy để tôi giải thích.",
    speaker: "none",
  },
  {
    id: 13,
    startTime: 103980,
    endTime: 109739,
    text: "There are many words in English which clearly contain a Y sound,",
    phonetic: "ðɛr ɑr ˈmɛni wɜrdz ɪn ˈɪŋɡlɪʃ wɪʧ ˈklɪrli kənˈteɪn ə waɪ saʊnd",
    translation: "Có nhiều từ trong tiếng Anh rõ ràng có âm Y,",
    speaker: "none",
  },
  {
    id: 14,
    startTime: 109739,
    endTime: 113931,
    text: "yet there is no Y in the spelling of the word.",
    phonetic: "jɛt ðɛr ɪz noʊ waɪ ɪn ðə ˈspɛlɪŋ əv ðə wɜrd",
    translation: "nhưng lại không có chữ Y trong cách viết từ đó.",
    speaker: "none",
  },
  {
    id: 15,
    startTime: 113931,
    endTime: 116883,
    text: "That's why I call them hidden.",
    phonetic: "ðæts waɪ aɪ kɔl ðəm ˈhɪdən",
    translation: "Đó là lý do tôi gọi chúng là âm ẩn.",
    speaker: "none",
  },
  {
    id: 16,
    startTime: 116883,
    endTime: 122277,
    text: "When two different vowels come together in a word,",
    phonetic: "wɛn tu ˈdɪfərənt ˈvaʊəlz kʌm təˈɡɛðər ɪn ə wɜrd",
    translation: "Khi hai nguyên âm khác nhau đứng cạnh nhau trong một từ,",
    speaker: "none",
  },
  {
    id: 17,
    startTime: 122277,
    endTime: 127935,
    text: "we often separate those two sounds with a hidden Y.",
    phonetic: "wi ˈɔfən ˈsɛpəˌreɪt ðoʊz tu saʊndz wɪð ə ˈhɪdən waɪ",
    translation: "chúng ta thường tách chúng bằng một âm Y ẩn.",
    speaker: "none",
  },
  {
    id: 18,
    startTime: 127935,
    endTime: 133664,
    text: "I'm going to give you some examples, but first, we're going to review the Y sound.",
    phonetic:
      "aɪm ˈɡoʊɪŋ tə ɡɪv ju səm ɪɡˈzæmpəlz bət fɜrst wɪr ˈɡoʊɪŋ tə rɪˈvju ðə waɪ saʊnd",
    translation:
      "Tôi sẽ đưa bạn một vài ví dụ, nhưng trước tiên, chúng ta sẽ ôn lại âm Y.",
    speaker: "none",
  },
  {
    id: 19,
    startTime: 133664,
    endTime: 138571,
    text: "It's a stretched sound. It's similar to a vowel.",
    phonetic: "ɪts ə strɛʧt saʊnd ɪts ˈsɪmələr tə ə ˈvaʊəl",
    translation: "Nó là một âm kéo dài. Nó giống với nguyên âm.",
    speaker: "none",
  },
  {
    id: 20,
    startTime: 138571,
    endTime: 140372,
    text: "Let's look at these words,",
    phonetic: "lɛts lʊk ət ðiz wɜrdz",
    translation: "Hãy cùng nhìn vào những từ này,",
    speaker: "none",
  },
  {
    id: 20,
    startTime: 138571,
    endTime: 140372,
    text: "Let's look at these words,",
    phonetic: "lɛts lʊk ət ðiz wɜrdz",
    translation: "Hãy cùng nhìn vào những từ này,",
    speaker: "none",
  },
  {
    id: 21,
    startTime: 140372,
    endTime: 145809,
    text: "and I want you to spin your hands on the Y sound, just so you really hear it well.",
    phonetic:
      "ənd aɪ wɑnt ju tə spɪn jʊr hændz ɑn ðə waɪ saʊnd ʤəst soʊ ju ˈrɪəli hɪr ɪt wɛl",
    translation:
      "và tôi muốn bạn xoay tay khi phát âm âm Y, để bạn thật sự nghe rõ nó.",
    speaker: "none",
  },
  {
    id: 22,
    startTime: 145809,
    endTime: 159090,
    text: "You, yesterday, repeat after me, yellow.",
    phonetic: "ju ˈjɛstərˌdeɪ rɪˈpit ˈæftər mi ˈjɛloʊ",
    translation: "Bạn, hôm qua, lặp lại theo tôi: màu vàng.",
    speaker: "none",
  },
  {
    id: 23,
    startTime: 159090,
    endTime: 165323,
    text: "So that's the Y sound, yuh, yuh.",
    phonetic: "soʊ ðæts ðə waɪ saʊnd jə jə",
    translation: "Đó chính là âm Y: yuh, yuh.",
    speaker: "none",
  },
  {
    id: 24,
    startTime: 165323,
    endTime: 166403,
    text: "That's it.",
    phonetic: "ðæts ɪt",
    translation: "Vậy đó.",
    speaker: "none",
  },
  {
    id: 25,
    startTime: 166403,
    endTime: 169590,
    text: "OK, now let's look at this word.",
    phonetic: "ˌoʊˈkeɪ naʊ lɛts lʊk ət ðɪs wɜrd",
    translation: "Được rồi, giờ hãy nhìn vào từ này.",
    speaker: "none",
  },
  {
    id: 26,
    startTime: 169590,
    endTime: 175131,
    text: "There is a very good chance that you mispronounce this word.",
    phonetic: "ðɛr ɪz ə ˈvɛri ɡʊd ʧæns ðət ju ˌmɪsprəˈnaʊns ðɪs wɜrd",
    translation: "Có khả năng cao là bạn phát âm sai từ này.",
    speaker: "none",
  },
  {
    id: 27,
    startTime: 175131,
    endTime: 181297,
    text: 'Many of my clients see this word, and they would say,"kreɪt", almost with one syllable.',
    phonetic:
      "ˈmɛni əv maɪ ˈklaɪənts si ðɪs wɜrd ənd ðeɪ wʊd seɪ kreɪt ˈɔlˌmoʊst wɪð wʌn ˈsɪləbəl",
    translation:
      "Nhiều khách hàng của tôi nhìn thấy từ này và họ sẽ nói “great”, gần như chỉ với một âm tiết.",
    speaker: "none",
  },
  {
    id: 28,
    startTime: 181297,
    endTime: 186473,
    text: "But this word actually has two syllables, not one, but two.",
    phonetic: "bət ðɪs wɜrd ˈækʧuəli hæz tu ˈsɪləbəlz nɑt wʌn bət tu",
    translation:
      "Nhưng từ này thực ra có hai âm tiết, không phải một mà là hai.",
    speaker: "none",
  },
  {
    id: 29,
    startTime: 186473,
    endTime: 191351,
    text: "And there's a hidden Y between the E and the A.",
    phonetic: "ənd ðɛrz ə ˈhɪdən waɪ bɪˈtwin ði i ənd ði eɪ",
    translation: "Và có một âm Y ẩn giữa chữ E và chữ A.",
    speaker: "none",
  },
  {
    id: 30,
    startTime: 191351,
    endTime: 196684,
    text: "We throw in a hidden Y to separate those two vowel sounds.",
    phonetic: "wi θroʊ ɪn ə ˈhɪdən waɪ tə ˈsɛpəˌreɪt ðoʊz tu ˈvaʊəl saʊndz",
    translation: "Chúng ta thêm một âm Y ẩn để tách hai âm nguyên âm đó ra.",
    speaker: "none",
  },
  {
    id: 31,
    startTime: 196821,
    endTime: 200679,
    text: "Let me show you how to say it. But first, we're going to have some fun.",
    phonetic: "lɛt mi ʃoʊ ju haʊ tə seɪ ɪt bət fɝst wɚ ɡoʊɪŋ tə hæv səm fʌn",
    translation:
      "Để tôi chỉ bạn cách nói điều đó. Nhưng trước tiên, chúng ta sẽ vui một chút.",
    speaker: "none",
  },
  {
    id: 32,
    startTime: 200679,
    endTime: 205879,
    text: "If you were to win a million dollars in a lottery, what would you say?",
    phonetic: "ɪf ju wɚ tə wɪn ə ˈmɪljən ˈdɑlərz ɪn ə ˈlɑtəri wʌt wʊd ju seɪ",
    translation: "Nếu bạn trúng một triệu đô trong xổ số, bạn sẽ nói gì?",
    speaker: "none",
  },
  {
    id: 33,
    startTime: 205879,
    endTime: 210028,
    text: "You would say, yay, yay.",
    phonetic: "ju wʊd seɪ jeɪ jeɪ",
    translation: 'Bạn sẽ nói: "Yay, yay".',
    speaker: "none",
  },
  {
    id: 34,
    startTime: 210269,
    endTime: 215418,
    text: "Now notice, there's a Y at the beginning and at the end of that.",
    phonetic: "naʊ ˈnoʊtɪs ðɛrz ə waɪ ət ðə bɪˈɡɪnɪŋ ənd ət ði ɛnd əv ðæt",
    translation: "Bây giờ hãy để ý, có chữ Y ở đầu và cuối từ đó.",
    speaker: "none",
  },
  {
    id: 35,
    startTime: 215418,
    endTime: 220721,
    text: "Yay, yay. You hear that?",
    phonetic: "jeɪ jeɪ ju hɪr ðæt",
    translation: "Yay, yay. Bạn nghe thấy không?",
    speaker: "none",
  },
  {
    id: 36,
    startTime: 220721,
    endTime: 225975,
    text: "Now we're going to put that yay into the word.",
    phonetic: "naʊ wɚ ɡoʊɪŋ tə pʊt ðæt jeɪ ˈɪntu ðə wɝd",
    translation: 'Giờ chúng ta sẽ đưa âm "yay" đó vào từ.',
    speaker: "none",
  },
  {
    id: 37,
    startTime: 225975,
    endTime: 232784,
    text: "Repeat after me. And we're going to do this in slow motion. There are three different parts.",
    phonetic:
      "rɪˈpit ˈæftɚ mi ænd wɚ ɡoʊɪŋ tə du ðɪs ɪn sloʊ ˈmoʊʃən ðɛr ɑr θri ˈdɪfɚənt pɑrts",
    translation:
      "Lặp lại theo tôi. Và chúng ta sẽ làm điều này chậm lại. Có ba phần khác nhau.",
    speaker: "none",
  },
  {
    id: 38,
    startTime: 232784,
    endTime: 234287,
    text: "Repeat after me.",
    phonetic: "rɪˈpit ˈæftɚ mi",
    translation: "Lặp lại theo tôi.",
    speaker: "none",
  },
  {
    id: 39,
    startTime: 234287,
    endTime: 247026,
    text: "Cree-yay-t, cree-yay-t, cree-yay-t. You see that?",
    phonetic: "kri-jeɪt kri-jeɪt kri-jeɪt ju si ðæt",
    translation: "Cree-yay-t, cree-yay-t, cree-yay-t. Bạn thấy không?",
    speaker: "none",
  },
  {
    id: 40,
    startTime: 247026,
    endTime: 252413,
    text: "Notice between the E and the A, there lives this hidden Y.",
    phonetic: "ˈnoʊtɪs bɪˈtwin ði i ænd ði eɪ ðɛr lɪvz ðɪs ˈhɪdən waɪ",
    translation: "Chú ý giữa chữ E và A, có một chữ Y ẩn ở đó.",
    speaker: "none",
  },
  {
    id: 41,
    startTime: 252413,
    endTime: 254542,
    text: "Cree-yay-t.",
    phonetic: "kri-jeɪt",
    translation: "Cree-yay-t.",
    speaker: "none",
  },
  {
    id: 42,
    startTime: 254542,
    endTime: 263506,
    text: "And this word is cree-yay-shin, cree-yay-shin.",
    phonetic: "ænd ðɪs wɝd ɪz kri-jeɪ-ʃən kri-jeɪ-ʃən",
    translation: "Và từ này là cree-yay-shin, cree-yay-shin.",
    speaker: "none",
  },
  {
    id: 43,
    startTime: 263506,
    endTime: 267193,
    text: "So let's look at this next word.",
    phonetic: "soʊ lɛts lʊk ət ðɪs nɛkst wɝd",
    translation: "Vậy hãy xem từ tiếp theo.",
    speaker: "none",
  },
  {
    id: 44,
    startTime: 267193,
    endTime: 274484,
    text: "Between the I and the O, those two vowels, there's another hidden Y.",
    phonetic: "bɪˈtwin ði aɪ ænd ði oʊ ðoʊz tu ˈvaʊəlz ðɛrz əˈnʌðɚ ˈhɪdən waɪ",
    translation: "Giữa chữ I và O, hai nguyên âm đó, có thêm một chữ Y ẩn nữa.",
    speaker: "none",
  },
  {
    id: 45,
    startTime: 274484,
    endTime: 277594,
    text: "This word actually has three syllables.",
    phonetic: "ðɪs wɝd ˈækʧuəli hæz θri ˈsɪləbəlz",
    translation: "Từ này thực ra có ba âm tiết.",
    speaker: "none",
  },
  {
    id: 46,
    startTime: 277594,
    endTime: 289273,
    text: "Ray-dee-yo, just like the toy, a yo-yo. Repeat, yo-yo.",
    phonetic: "ˈreɪ-di-oʊ ʤəst laɪk ðə tɔɪ ə ˈjoʊ-ˌjoʊ rɪˈpit ˈjoʊ-joʊ",
    translation: "Ray-dee-yo, giống như món đồ chơi yo-yo. Lặp lại: yo-yo.",
    speaker: "none",
  },
  {
    id: 47,
    startTime: 289273,
    endTime: 295281,
    text: "Ray-dee-yo, ray-dee-yo.",
    phonetic: "ˈreɪ-di-oʊ ˈreɪ-di-oʊ",
    translation: "Ray-dee-yo, ray-dee-yo.",
    speaker: "none",
  },
  {
    id: 48,
    startTime: 295281,
    endTime: 304918,
    text: "And this word is the same thing, three syllables, vid-ee-yo, vid-ee-yo.",
    phonetic: "ænd ðɪs wɝd ɪz ðə seɪm θɪŋ θri ˈsɪləbəlz ˈvɪd-i-oʊ ˈvɪd-i-oʊ",
    translation: "Và từ này cũng vậy, ba âm tiết: vid-ee-yo, vid-ee-yo.",
    speaker: "none",
  },
  {
    id: 49,
    startTime: 304918,
    endTime: 314915,
    text: "Now, many of my clients would say these words with only two syllables. They would say radio, video, but they're actually three syllables.",
    phonetic:
      "naʊ ˈmɛni əv maɪ ˈklaɪənts wʊd seɪ ðiz wɝdz wɪð ˈoʊnli tu ˈsɪləbəlz ðeɪ wʊd seɪ ˈreɪdioʊ ˈvɪdioʊ bət ðɛr ˈækʧuəli θri ˈsɪləbəlz",
    translation:
      "Nhiều học viên của tôi thường nói những từ này chỉ với hai âm tiết. Họ nói radio, video, nhưng thực ra chúng có ba âm tiết.",
    speaker: "none",
  },
  {
    id: 50,
    startTime: 314915,
    endTime: 320394,
    text: "Ray-dee-yo, vid-ee-yo.",
    phonetic: "ˈreɪ-di-oʊ ˈvɪd-i-oʊ",
    translation: "Ray-dee-yo, vid-ee-yo.",
    speaker: "none",
  },
  {
    id: 51,
    startTime: 320394,
    endTime: 324509,
    text: "Very good. Look at this word.",
    phonetic: "ˈvɛri ɡʊd lʊk ət ðɪs wɝd",
    translation: "Rất tốt. Nhìn vào từ này.",
    speaker: "none",
  },
  {
    id: 52,
    startTime: 324509,
    endTime: 330742,
    text: "Between the E vowel and the O vowel, you'll find another hidden Y.",
    phonetic:
      "bɪˈtwin ði i ˈvaʊəl ænd ði oʊ ˈvaʊəl juːl faɪnd əˈnʌðɚ ˈhɪdən waɪ",
    translation:
      "Giữa nguyên âm E và nguyên âm O, bạn sẽ thấy một chữ Y ẩn khác.",
    speaker: "none",
  },
  {
    id: 53,
    startTime: 330742,
    endTime: 340157,
    text: "Dee-yo-der-ent, dee-yo-der-ent. That's how you say it, dee-yo-der-ent.",
    phonetic: "ˈdi-oʊ-dɚ-rənt ˈdi-oʊ-dɚ-rənt ðæts haʊ ju seɪ ɪt ˈdi-oʊ-dɚ-rənt",
    translation:
      "Dee-yo-der-ent, dee-yo-der-ent. Đó là cách bạn nói, dee-yo-der-ent.",
    speaker: "none",
  },
  {
    id: 54,
    startTime: 340157,
    endTime: 346573,
    text: "He needs deodorant. Repeat.",
    phonetic: "hi nidz diˈoʊdɚrənt rɪˈpit",
    translation: "Anh ấy cần lăn khử mùi. Lặp lại.",
    speaker: "none",
  },
  {
    id: 55,
    startTime: 348349,
    endTime: 354536,
    text: "Very good. OK, I'll see you in the next video class, where we will be covering more hidden Y sounds,",
    phonetic:
      "ˈvɛri ɡʊd oʊˈkeɪ aɪl si ju ɪn ðə nɛkst ˈvɪdioʊ klæs wɛr wi wɪl bi ˈkʌvərɪŋ mɔr ˈhɪdən waɪ saʊndz",
    translation:
      "Rất tốt. Được rồi, hẹn gặp bạn trong lớp video tiếp theo, nơi chúng ta sẽ học thêm về các âm Y ẩn.",
    speaker: "none",
  },
  {
    id: 56,
    startTime: 354536,
    endTime: 359711,
    text: "specifically when you're going from an I vowel to an R.",
    phonetic: "spəˈsɪfɪkli wɛn jɚ ˈɡoʊɪŋ frəm ən aɪ ˈvaʊəl tu ən ɑr",
    translation: "Cụ thể là khi bạn chuyển từ nguyên âm I sang âm R.",
    speaker: "none",
  },
  {
    id: 57,
    startTime: 359758,
    endTime: 361401,
    text: "And I'll see you there.",
    phonetic: "ænd aɪl si ju ðɛr",
    translation: "Và tôi sẽ gặp bạn ở đó.",
    speaker: "none",
  },
];

export const subtitle4: SubtitleEntry[] = [...sub4];
export const subtitle5: SubtitleEntry[] = [...sub5];
